### ISSUE TITLE
Is the Badger stream framework supported?

### ISSUE THREAD

**Issue by davedbase** [timshannon/badgerhold#45]
I was wondering if Bagderhold can support stream (https://dgraph.io/docs/badger/get-started/#stream) if not is it a major enhancement or minor and easy to adapt?

**Comment by timshannon** [comment]
I'm not sure how it would apply to Badgerhold which is a querying layer on top of Badger.  You can easily use this stream functionality with Badgerhold by simply accessing the underlying Badger database: https://godoc.org/github.com/timshannon/badgerhold#Store.Badger

```Go
store, err := badgerhold.Open(opt)
if err != nil {
	t.Fatalf("Error opening %s: %s", opt.Dir, err)
}

stream := store.Badger().NewStream()
// db.NewStreamAt(readTs) for managed mode.

// -- Optional settings
stream.NumGo = 16                     // Set number of goroutines to use for iteration.
stream.Prefix = []byte("some-prefix") // Leave nil for iteration over the whole DB.
stream.LogPrefix = "Badger.Streaming" // For identifying stream logs. Outputs to Logger.

// ChooseKey is called concurrently for every key. If left nil, assumes true by default.
stream.ChooseKey = func(item *badger.Item) bool {
  return bytes.HasSuffix(item.Key(), []byte("er"))
}

```

All of the index, type, and encoding information that Badgerhold uses is stored in the badger database, so that will all get streamed along with your data.

**Comment by davedbase** [comment]
Gotcha. Thanks.
